stages:
  - deploy

default:
  image: $NEXUS_REGISTRY/devops:latest
  tags:
    - RND-INFRA

.deploy-prep: &deploy-prep
  when: manual
  before_script:
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - echo "$SSH_PRIVATE_KEY" > ssh_key
    - chmod 400 ssh_key
    - eval $(ssh-agent -s)
    - ssh-add ssh_key
    - rm ssh_key

deploy-loki:
  <<: *deploy-prep
  stage: deploy
  when: manual
  services:
    - docker:dind
  script:
    - ansible-playbook -i hosts grafana_loki.yml -u root
    - ansible-playbook -i hosts rnd_grafana_loki_dev.yml -u root
    - ansible-playbook -i hosts rnd_grafana_loki_uat.yml -u root
    - ansible-playbook -i hosts rnd_grafana_loki_live.yml -u root

deploy-grafana:
  <<: *deploy-prep
  stage: deploy
  when: manual
  services:
    - docker:dind
  script:
    - ansible-playbook -i hosts grafana_tv.yml -u root -e "grafana_ldap_user=$GRAFANA_LDAP_USER grafana_ldap_password=$GRAFANA_LDAP_PASSWORD GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD"
    - ansible-playbook -i hosts grafana.yml -u root -e "grafana_ldap_user=$GRAFANA_LDAP_USER grafana_ldap_password=$GRAFANA_LDAP_PASSWORD GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD"
