- name: Create a Grafana configuration directory
  file:
    path: /etc/grafana-test
    state: directory
    mode: '0755'
    owner: "1001"
    group: "1001"

- name: Create a docker volume for grafana-test with options
  docker_volume:
    name: grafana-test-data
    driver_options:
      type: block
      device: /home/grafana-test-data
      o: bind

- name: Copy grafana configuration
  copy:
    src: grafana.ini
    dest: /etc/grafana-test/grafana.ini

- name: Substitute variables in the template file
  template:
    src: ldap.toml.template
    dest: /etc/grafana-test/ldap.toml
    mode: '0644'

# ------------------- NEW: Plugin cleanup and install BEFORE container start -------------------

- name: Ensure Zabbix plugin directory is clean
  shell: >
    docker run --rm
    -v grafana-test-data:/var/lib/grafana
    alpine sh -c 'rm -rf /var/lib/grafana/plugins/alexanderzobnin-zabbix-app'
  args:
    executable: /bin/sh

- name: Pre-install Zabbix plugin 5.1.0 into Grafana volume
  shell: >
    docker run --rm
    --entrypoint "/bin/bash"
    -v grafana-test-data:/var/lib/grafana
    -e GF_PATHS_PLUGINS=/var/lib/grafana/plugins
    grafana/grafana:10.4.1
    -c "grafana-cli plugins install alexanderzobnin-zabbix-app 5.1.0"

# ------------------- THEN start the container -------------------

- name: Start Grafana
  docker_container:
    name: grafana-test
    image: grafana/grafana:10.4.1
    networks:
      - name: fltechnics
    state: started
    restart_policy: always
    published_ports:
      - "3012:3000"
    volumes:
      - grafana-test-data:/var/lib/grafana
      - /etc/grafana-test:/etc/grafana
    env:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: "{{ GF_SECURITY_ADMIN_PASSWORD }}"
      GF_USERS_ALLOW_SIGN_UP: "false"