
- name: Create a Grafana configuration directory
  file:
    path: /home/grafana-tv-data
    state: directory

- name: Create a docker volume for grafana with options
  docker_volume:
    name: grafana-tv-data
    driver_options:
      type: block
      device: /home/grafana-tv-data
      o: bind

- name: Create a grafana configuration directory
  file:
    path: /etc/grafana-tv
    state: directory
    mode: '0755'
    owner: "1001"
    group: "1001"

- name: Copy grafana configuration
  copy:
    src: grafana.ini
    dest: /etc/grafana-tv/grafana.ini

- name: Substitute variables in the template file
  template:
    src: ldap.toml.template
    dest: /etc/grafana-tv/ldap.toml
    mode: '0644'
    
- name: Start Grafana
  docker_container:
    name: grafana-tv
    image: grafana/grafana:7.1.5
    networks:
      - name: fltechnics
    state: started
    restart_policy: always
    published_ports:
      - "3011:3000"
    volumes:
      - grafana-tv-data:/var/lib/grafana
      - /etc/grafana-tv:/etc/grafana
    env: 
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: "{{ GF_SECURITY_ADMIN_PASSWORD }}"
        GF_USERS_ALLOW_SIGN_UP: "false"
